# evaluate.py: rank TOP 10 most novel rewakeouts (relative evaluation)
# Default I/O directory: reports/
# Usage:
#   python evaluate.py 1ogo_time_space.csv
#   python evaluate.py 1ogo_time_space.csv --model gpt-5.2
#   python evaluate.py 1ogo_time_space.csv --model gemini
# Output:
#   reports/top10_1ogg.csv

from __future__ import annotations
import argparse
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List
import pandas as pd
import requests

REPORTS_DIR = Path("reports")

_JSON_OBJ_RE = re.compile(r"\{.*\}", re.DOTALL)

def extract_json_object(text: str) -> Dict[str, Any]:
    m = _JSON_OBJ_RE.search((text or "").strip())
    if not m:
        raise ValueError("No JSON object found in model output")
    return json.loads(m.group(0))

def _normalize_top10(obj: Dict[str, Any]) -> Dict[str, Any]:
    if "top10" in obj:
        return obj
    # list under any key
    for v in obj.values():
        if isinstance(v, list) and len(v) >= 1 and isinstance(v[0], dict):
            return {"top10": v}
    # rank-keyed dict: {"1": {run_id, ...}, "2": ..., "10": ...}
    int_keys = sorted([k for k in obj if str(k).isdigit()], key=int)
    if len(int_keys) >= 10:
        items = []
        for k in int_keys[:10]:
            entry = dict(obj[k])
            entry.setdefault("rank", int(k))
            items.append(entry)
        return {"top10": items}
    raise ValueError(f"Cannot find top10 list in response: {list(obj.keys())}")

def default_suffix_from_path(p: Path) -> str:
    stem = p.stem
    if stem.startswith("top_rewakeout_"):
        return stem.replace("top_rewakeout_", "")
    return stem

def build_entries(df: pd.DataFrame, max_entries: int, max_chars: int) -> str:
    lines: List[str] = []
    n = min(len(df), max_entries)

    for i in range(n):
        run_id = int(df.iloc[i]["run_id"])
        text = str(df.iloc[i]["text"]).strip()   # ← ここ変更

        if max_chars > 0 and len(text) > max_chars:
            text = text[:max_chars] + "…"

        lines.append(
            f'[run_id={run_id}]\n'
            f'{text}'
        )

    return "\n".join(lines)

def build_prompt(entries_text: str) -> tuple[str, str]:
    system = (
        "You are a strict evaluator of novelty in ideas.\n"
        "Rank ideas RELATIVE to each other.\n"
        "Be decisive.\n"
    )
    user = (
        "Below are candidate ideas generated by an AI.\n"
        "Each entry has a run_id and an idea (rewakeout).\n\n"
        "Task:\n"
        "Select the TOP 10 most novel ideas relative to the others.\n\n"
        "Criteria:\n"
        "- Unexpected conceptual connections\n"
        "- Non-obvious abstraction or reframing\n\n"
        "Do NOT reward:\n"
        "- Standard textbook explanations\n"
        "- Familiar metaphors without new insight\n\n"
        "Return JSON with exactly 10 items:\n"
        "- rank (1–10)\n"
        "- run_id\n"
        "- short_justification (1–2 sentences)\n\n"
        "Entries:\n"
        f"{entries_text}"
    )
    return system, user

@dataclass
class OpenAIRanker:
    api_key: str
    model: str = "gpt-5-mini"
    base_url: str = "https://api.openai.com/v1"
    timeout_s: int = 180

    def rank(self, entries_text: str, max_tokens: int) -> Dict[str, Any]:
        system, user = build_prompt(entries_text)
        url = f"{self.base_url.rstrip('/')}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload: Dict[str, Any] = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "max_completion_tokens": max_tokens,
        }
        if self.model in ("gpt-5-mini",):
            payload["reasoning_effort"] = "minimal"
            payload["response_format"] = {"type": "json_object"}
        else:
            payload["temperature"] = 0.0
            schema = {
                "name": "top10_rank",
                "schema": {
                    "type": "object",
                    "properties": {
                        "top10": {
                            "type": "array",
                            "minItems": 10,
                            "maxItems": 10,
                            "items": {
                                "type": "object",
                                "properties": {
                                    "rank": {"type": "integer", "minimum": 1, "maximum": 10},
                                    "run_id": {"type": "integer"},
                                    "short_justification": {"type": "string"},
                                },
                                "required": ["rank", "run_id", "short_justification"],
                                "additionalProperties": False,
                            },
                        }
                    },
                    "required": ["top10"],
                    "additionalProperties": False,
                },
            }
            payload["response_format"] = {"type": "json_schema", "json_schema": schema}

        r = requests.post(url, headers=headers, json=payload, timeout=self.timeout_s)
        r.raise_for_status()
        content = r.json()["choices"][0]["message"]["content"]
        return _normalize_top10(json.loads(content))


@dataclass
class GeminiRanker:
    api_key: str
    model: str = "gemini-3-flash-preview"
    timeout_s: int = 180

    def rank(self, entries_text: str, max_tokens: int) -> Dict[str, Any]:
        system, user = build_prompt(entries_text)
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
        params = {"key": self.api_key}
        headers = {"Content-Type": "application/json"}
        payload = {
            "contents": [{"role": "user", "parts": [{"text": system + "\n\n" + user}]}],
            "generationConfig": {
                "temperature": 0.0,
                "maxOutputTokens": max_tokens,
                "responseMimeType": "application/json",
            },
        }
        r = requests.post(url, params=params, headers=headers, json=payload, timeout=self.timeout_s)
        if r.status_code >= 400:
            raise RuntimeError(f"Gemini HTTP {r.status_code}: {r.text[:500]}")
        text = r.json()["candidates"][0]["content"]["parts"][0]["text"]
        return json.loads(text)

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", help="top_rewakeout_XXXX.csv (default dir: reports/)")
    ap.add_argument("--model", choices=["gpt-5-mini", "gpt-5.2", "gemini"], default="gpt-5-mini")
    ap.add_argument("--gemini-model", type=str, default="gemini-3-flash-preview")
    ap.add_argument("--max-entries", type=int, default=80)
    ap.add_argument("--max-chars", type=int, default=1200)
    ap.add_argument("--max-tokens", type=int, default=1600)
    args = ap.parse_args()

    # ---- input path resolution ----
    in_path = Path(args.csv)
    if not in_path.exists():
        candidate = REPORTS_DIR / in_path.name
        if candidate.exists():
            in_path = candidate
        else:
            raise FileNotFoundError(in_path)

    df = pd.read_csv(in_path)
    if "text" not in df.columns:
        if "rewakeout" in df.columns:
            df["text"] = df["rewakeout"]
        else:
            raise ValueError("CSV must contain run_id and text (or rewakeout)")

    # ---- 有効テキストの抽出（ここ追加）----
    # NaN/空白だけを落とす
    df["text"] = df["text"].astype(str)
    valid_mask = df["text"].notna() & (df["text"].str.strip() != "") & (df["text"].str.lower().str.strip() != "nan")
    df_valid = df.loc[valid_mask].copy()

    n_total = len(df)
    n_valid = len(df_valid)
    n_used = min(n_valid, args.max_entries)

    print(f"[evaluate] input rows     = {n_total}")
    print(f"[evaluate] valid text rows = {n_valid}")
    print(f"[evaluate] used for ranking = {n_used} (max_entries={args.max_entries})")

    # 以降は df ではなく df_valid を使う
    df = df_valid

    suffix = default_suffix_from_path(in_path)
    # ---- output paths (always reports/) ----
    REPORTS_DIR.mkdir(exist_ok=True)
    out_json = REPORTS_DIR / f"top10_{suffix}.json"
    out_csv  = REPORTS_DIR / f"top10_{suffix}.csv"

    entries_text = build_entries(df, args.max_entries, args.max_chars)

    if args.model == "gemini":
        api_key = os.environ.get("GEMINI_API_KEY", "")
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY not set")
        ranker = GeminiRanker(api_key=api_key, model=args.gemini_model)
    else:
        api_key = os.environ.get("OPENAI_API_KEY", "")
        if not api_key:
            raise RuntimeError("OPENAI_API_KEY not set")
        ranker = OpenAIRanker(api_key=api_key, model=args.model)

    valid_run_ids = set(df["run_id"].astype(int))
    bad: list = []
    for attempt in range(3):
        result = ranker.rank(entries_text, args.max_tokens)
        top10 = result["top10"]
        bad = [r["run_id"] for r in top10
               if str(r.get("run_id", "")).split("_")[0].isdigit()
               and int(str(r["run_id"]).split("_")[0]) not in valid_run_ids]
        if not bad:
            break
        print(f"[warn] attempt {attempt+1}: hallucinated run_ids={bad}, retrying…")
    if bad:
        print(f"[warn] giving up after 3 attempts; {len(bad)} invalid run_ids remain")

    result_df = pd.DataFrame(result["top10"])
    score_cols = [c for c in ["cond", "alignment", "coherence", "novelty"] if c in df.columns]
    if score_cols:
        score_map = df.drop_duplicates(subset="run_id").set_index("run_id")[score_cols]
        insert_at = result_df.columns.get_loc("run_id") + 1
        for i, col in enumerate(score_cols):
            result_df.insert(insert_at + i, col, result_df["run_id"].map(score_map[col]))
    #out_json.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    result_df.to_csv(out_csv, index=False, encoding="utf-8-sig")

    print(f"[saved] {out_json}")
    print(f"[saved] {out_csv}")

if __name__ == "__main__":
    main()